create table table_order
(
	id integer generated by default as identity
		constraint table_order_pkey
			primary key
);

alter table table_order owner to postgres;

create table order_item
(
	id integer generated by default as identity
		constraint order_item_pkey
			primary key,
	item varchar(255) not null,
	quantity integer not null,
	table_id integer
		constraint fksk1yo2clqyqladoop275d4twd
			references table_order
);

alter table order_item owner to postgres;

